# Generated by Django 5.0.7 on 2024-08-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("created_at", "views_count"),
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
