# Generated by Django 5.0.7 on 2024-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_version_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(verbose_name="Номер версии"),
        ),
    ]
